spring.application.name=employee

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Quocnhan123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=YourSuperSecretKeyThatIsAtLeast32CharactersLongForJWTValidation=
app.jwt.expirationMs=86400000

server.port=8085

grpc.server.port=9093

logging.level.io.grpc=DEBUG

grpc.client.payroll-server.address=static://localhost:9091
grpc.client.payroll-server.negotiation-type=plaintext

grpc.client.attendance-server.address=static://localhost:9092
grpc.client.attendance-server.negotiation-type=plaintext
