spring.application.name=attendance_service
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_service
spring.datasource.username=root
spring.datasource.password=Quocnhan123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=YourSuperSecretKeyThatIsAtLeast32CharactersLongForJWTValidation=
app.jwt.expirationMs=86400000

#grpc.client.employee-service.address=static://localhost:9092
#grpc.client.employee-service.negotiationType=PLAINTEXT

grpc.server.port=9092

server.port=8081