spring:
  application:
    name: department_service

  datasource:
    url: "jdbc:mysql://localhost:3306/department_service"
    username: root
    password: Quocnhan123@
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8086


jwt:
  signerKey: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForJWTValidation="
